sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

# skip the installation step - we have no requirements here
install: true

script:
  - python3 -m unittest tests.test_unrar_wrapper
